version: "3.1"
nlu:
- intent: osnovaniya_academ_mob
  examples: |
    - основания для академической мобильности
    - основании для академической мобильности
- intent: poslednii_god_academ_mob
  examples: |
    - Можно ли участвовать в академической мобильности в последнем семестре
    - Можно ли участвовать в мобильности в последний семестр обучения и как защищать диплом?
- intent: voennaia_kafedra_academ_mob
  examples: |
    - Могут ли студенты, которые учатся на военной кафедре, участвовать в программе мобильности?
    - что делать если я учусь на военной кафедре и хочу поехать по обмену
- intent: kriterii_otbora_academ_mob
  examples: |
    - академическая мобильность какие критерии
    - какие критерии для академической мобильности
    - какие критерии для мобильности по обмену
- intent: sroki_academ_mob
  examples: |
    - мобильность по обмену сроки какие
    - Сроки подачи документов на участие в программе академической мобильности
    - академическая мобильность сроки какие
- intent: otkaz_academ_mob
  examples: |
    - что будет если передумать поехать по обмену
    - что будет если отказаться от мобильности
    - можно ли отказаться от академической мобильности
- intent: freemover_academ_mob
  examples: |
    - freemover в мобильности
    - Возможно ли обучение в вузе, которого нет в списке партнеров по академической мобильности (freemover)?
    - можно ли выбрать другой универ для обмена
- intent: result_academ_mob
  examples: |
    - что получим в конце академической мобильности
    - Какой подтверждающий документ мы получим при успешном окончании обучения по программе академической мобильности?
    - что даст обучение по мобильности
- intent: grant_withdrawal
  examples: |
    - лишение гранта
    - Какие действия могут привести к лишению гранта?
    - Могу ли я потерять грант из-за неудовлетворительной успеваемости?
- intent: get_transcript
  examples: |
    - Могу ли я увидеть свой транскрипт онлайн?
    - Где могу получить свой транскрипт?
    - Как получить транскрипт?
- intent: no_grades
  examples: |
    - Что делать, если оценка не появилась в системе?
    - нету оценки
    - Мне не поставили оценку, куда обращаться?
- intent: cabinets_of_faculty
  examples: |
    - Где я могу найти номера кафедр?
    - Где находится кафедра КИ, КБ, МКМ, РЭТ? И их номер?
    - Как найти кафедру КИ, КБ, МКМ, РЭТ?
- intent: who_is_adviser
  examples: |
    - Кто эдвайзер
    - Какова роль эдвайзера в университете?
    - Кто такой эдвайзер?
- intent: return_overpayed_money_tuition
  examples: |
    - вернут переплаченную за обучение денежную сумму
    - Я переплатил за обучение, как мне вернуть деньги?
    - Как можно вернуть переплаченную за обучение денежную сумму?
- intent: what_is_academic_calendar
  examples: |
    - Где мне найти академический календарь?
    - где можно с ним ознакомиться c академический календарем?
    - Что такое академический календарь?
- intent: extend_midterms
  examples: |
    - Могу ли я продлить сроки Рубежного контроля?
    - При каких обстоятельствах можно продлить Рубежный контроль?
    - В каких случаях можно продлить рк
- intent: extend_finals
  examples: |
    - При каких условиях можно продлить сессию?
    - В каких случаях можно продлить сессию?
    - Могу ли я перенести дату экзамена?
- intent: academic_internship
  examples: |
    - Как я могу зарегистрироваться на учебную практику?
    - Что такое учебная и производственная практика?
    - Что такое учебная практика?
- intent: change_group
  examples: |
    - Что необходимо для перевода в другую образовательную программу?
    - Как можно поменять образовательную программу?
    - Как можно поменять образовательную группу?
- intent: recourse
  examples: |
    - При каких условиях можно перейти на перекурс?
    - В каких случаях у студентов может быть перекурс?
    - Как подать заявление на перекурс?
- intent: finals_earlier
  examples: |
    - Можно ли сдать экзамен заранее?
    - Можно ли сдать сессию пораньше?
    - Можно ли сдать экзаменационную сессию пораньше?
- intent: free_from_studies
  examples: |
    - Как я могу получить свободное посещение занятий?
    - При каких случаях оформляется свободное посещение?
    - При каких условиях можно оформить свободное посещение?
- intent: summer_semestr
  examples: |
    - Что входит в программу летнего семестра?
    - летний семестр
    - Как записаться на летний семестр?
- intent: lost_my_stuff
  examples: |
    - Я потерял свою вещь в университете, куда я должен обратиться?
    - Куда обращаться если я потерял вещь в университете?
    - потерял вещи
- intent: travel_allowance
  examples: |
    - Какие документы необходимы для получения дорожных выплат?
    - Как часто выплачиваются дорожные выплаты?
    - когда можно получить дорожные выплаты?
- intent: polyclinic_out_of_town_students
  examples: |
    - Какую поликлинику выбрать для иногороднего студента?
    - Как происходит прикрепление к поликлинике для иногородних студентов?
    - Куда необходимо прикрепиться иногороднему студенту?
- intent: poteryal_onay
  examples: |
    - Я потерял свою транспортную карточку Онай, что делать?
    - Как восстановить утерянную транспортную карточку Онай?
    - Что нужно сделать, если я потерял Онай?
    - потерял онай
- intent: kolledj_kak_poluchit_onay
  examples: |
    - Как получить Онай выпускникам колледжей?
    - Как оформить Онай, если я окончил колледж?
    - Что нужно предпринять, чтобы получить Онай после колледжа?
    - Как выпускникам колледжей получить транспортную карточку Онай?
- intent: inostranec_kak_poluchit_onay
  examples: |
    - Как получить Онай иностранным студентам?
    - Что нужно делать, чтобы получить Онай, если я иностранный студент?
    - Как оформить Онай для иностранных студентов?
    - Как иностранным студентам получить транспортную карточку Онай?
- intent: prosyat_oplatu_coursera
  examples: |
    - Как оплатить курсы на Coursera?
    - Почему требуется оплата за курсы на Coursera?
    - Я хочу пройти курсы на Coursera, но мне сообщают о необходимости оплаты. Что делать?
    - Я не могу пройти курсы в Coursera, просят произвести оплату
- intent: netu_priglachenie_coursera
  examples: |
    - Как получить приглашение на Coursera?
    - Я не могу найти приглашение на Coursera. Что делать?
    - Где найти приглашение для доступа к курсам на Coursera?
    - в курсере нету приглашение
- intent: drugie_kursy_coursera
  examples: |
    - Какие ещё курсы доступны на Coursera?
    - Есть ли дополнительные курсы на Coursera, которые я могу пройти?
    - Могу ли я выбрать и проходить другие курсы на Coursera, помимо обязательных?
    - Могу я пройти другие курсы, помимо обязательных?
- intent: starye_kursy_coursera
  examples: |
    - Как удалить старые курсы из профиля на Coursera?
    - в курсере остались старые курсы
    - Можно ли обновить информацию о пройденных курсах на Coursera?
    - Я поменял специальность, но в Coursera осталась старая
- intent: retake_coursera
  examples: |
    - Мне нужно пройти ретейк через Coursera, как мне получить доступ?
    - Как пройти пересдачу курса на Coursera?
    - Я хочу пройти ретейк курса на Coursera. Как получить доступ для пересдачи?
    - Что нужно сделать для того, чтобы пройти ретейк на Coursera?
- intent: academ_mob
  examples: |
    - академическая мобильность
    - учеба по обмену
    - хочу задать вопрос насчет учебы по обмену
    - вопросы насчет академической мобильности
- intent: uchebnaia_uspevaemost_academ_mob
  examples: |
    - Как учебная успеваемость влияет на результаты отбора  в программе академической мобильности?
    - академическая мобильность учебная успеваемость влияет
    - Как учебная успеваемость влияет на результаты отбора для академической мобильности
    - оценки влияют в отборе по академической мобильности
- intent: v_muit_perevod
  examples: |
    - Как мне перевестись в МУИТ?
    - Как можно перевестись в МУИТ?
    - как перевестись в муит
    - Какой процесс перевода в МУИТ?
- intent: v_drugoi_universitet_perevod
  examples: |
    - Как перевестись в другой унисерситет?
    - Какие документы требуются для перевода в другой университет?
    - Как осуществить перевод в другой университет?
    - Как я могу перевестись в другой университет?
- intent: lishenie_granta_perevod
  examples: |
    - Лишают ли гранта при переводе из одного университета в другой?
    - Лишается ли студент государственного образовательного гранта при переводе?
    - Какие последствия перевода для получения гранта?
    - лишение гранта при переводе
- intent: expulsion
  examples: |
    - Как избежать отчисления?
    - отчисление
    - Какие причины могут привести к отчислению?
    - Каковы правила отчисления студентов?
- intent: academic_vacation
  examples: |
    - Могу ли я взять академический отпуск из-за болезни?
    - В каких случаях предоставляется академический отпуск?
    - В каких случаях предоставляется академический перерыв?
    - Как взять академический отпуск?
- intent: ill_during_exams
  examples: |
    - Что делать в случае болезни во время экзаменов?
    - Как пройти экзамены, если я заболел?
    - Что если я заболею на экзаменах?
    - Что делать если я заболел во время прохождения рубежного экзаменационной сессии?
- intent: several_retakes
  examples: |
    - Что делать при нескольких пересдачах?
    - Сколько ритейков можно иметь в одном семестре?
    - Как можно избежать ритейков?
    - Что делать если у меня несколько ритейков?
- intent: mesta_ucheby_spravka
  examples: |
    - справка с места учебы
    - Какие шаги нужно предпринять для получения справки с места учебы?
    - Что необходимо для получения справки с места учебы?
    - Мне нужна справка с места учебы, как ее получить?
    - Где я могу получить справку с места учебы?
- intent: gosudarstvennye_posobiya_spravka
  examples: |
    - справка чтобы получить государственное пособие
    - Как можно получить справку для получения государственных пособий для предъявления в государственный центр по выплате пенсий (ГЦВП)?
    - Как получить справку для ГЦВП?
    - Где мне взять справку для получения государственных пособий?
    - Как мне оформить справку для ГЦВП?
- intent: voenkomat_spravka
  examples: |
    - Где я могу взять справку для военкомата?
    - Как можно получить справку для военкомата?
    - Что мне нужно для получения справки для военкомата?
    - справка для военкомата
    - Как получить справку для военкомата?
- intent: coursera
  examples: |
    - курсера
    - у меня вопросы насчет курсеры
    - coursera
    - курсеро
    - подскажи насчет курсеры
- intent: chto_takoe_academ_mob
  examples: |
    - объясни что такое академическая мобильность
    - что такое академическая мобильность
    - че за академическая мобильность
    - объясни академическую мобильность
    - что с собой представляет академ мобильность
- intent: spravka
  examples: |
    - справка
    - как получить справку
    - справку
    - вопросы насчет справки
    - подскажи как получить справку
    - нужна справка
- intent: kak_poluchit_onay
  examples: |
    - Какая процедура получения транспортной карточки Онай?
    - Какой адрес нужно посетить для получения Онай?
    - Какие документы нужны для получения Онай?
    - Как я могу получить Онай?
    - как получить онай
    - хочу карточку онай
- intent: ielts_academ_mob
  examples: |
    - нужно ли сдавать toefl для академической мобильности
    - нужно ли сдавать айлтс для академической мобильности
    - айлтс нужно для академической мобильности
    - нужно ли сдавать тойфл для академической мобильности
    - тойфл нужно для академической мобильности
    - нужно ли сдавать ielts для академической мобильности
- intent: perevod
  examples: |
    - Что нужно предпринять, чтобы осуществить перевод?
    - вопросы насчет перевода
    - Какие условия необходимо выполнить для перевода?
    - как перевестись
    - перевод
    - Я хотел бы узнать о процессе перевода
- intent: obrazec_recom_academ_mob
  examples: |
    - образец для рекомендашки
    - образец рекомендашки
    - форма рекомендашки
    - образец рекомендательного письма
    - форма рекомендательного письма
    - Есть ли форма для составления рекомендательного письма?
    - форма для рекомендашки
- intent: onay
  examples: |
    - хочу получит онай
    - нужно онай
    - онай
    - вопросы насчет оңай
    - онайка
    - вопросы насчет онай
    - оңай
    - нужен онай
    - вопросы насчет онайки
- intent: out_of_scope
  examples: |
    - вж жфы йууй
    - цуу цуу цуу
    - й
    - зызызы
    - ююю
    - жйжйжй
    - ввф йц
    - жв фы цуу
    - афвв ццц
    - нонсенс
    - аф вв
    - ничего не понимаю
    - хаос
    - абвгдеё
    - бла бла бла
    - ж
- intent: goodbye
  examples: |
    - досвидания
    - до следующего раза
    - до встречи
    - прощайте
    - спасибо
    - удачи
    - всего наилучшего
    - пока
    - спасибо за помощь
    - спасибо и до свидания
    - до свидания
    - всего доброго
    - до новых встреч
    - увидимся
    - окей спасибо
    - прощай
- intent: greet
  examples: |
    - здравия желаю
    - приветик
    - салам
    - как делишки?
    - здравствуй, добрый день
    - рад тебя видеть
    - ассаламу алейкум
    - start
    - здравствуйте, добрый день
    - как житуха?
    - добрый вечер
    - доброго времени суток
    - как твои дела?
    - ало
    - здравствуй, как дела?
    - салам алейкум
    - как дела?
    - доброе утро
    - привет
    - здравствуй
    - саламалейкум
    - здравствуйте
